apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-lt
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [${azs}]                               #Update the correct region and zones
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    launchTemplate: "karpenter-${eks-cluster-id}"     # Used by Karpenter Nodes
    subnetSelector:
      Name: "${eks-vpc_name}-private*"
  labels:
    type: karpenter
    provisioner: default-lt
  taints:
    - key: default-lt
      value: 'true'
      effect: NoSchedule
  ttlSecondsAfterEmpty: 120
